name: nftgen
description: NFT unique image generator and metadata analyzer, available as package and CLI.
version: 0.0.4
homepage: https://github.com/xErik/nftgen
keywords: nft, crypto

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  args: ^2.3.1
  crypto: ^3.0.2
  image: ^4.0.8
  io: ^1.0.3
  path: ^1.8.2
