name: nftgen
description: NFT unqiue image generator and metadata analyzer, available on library and command line.
version: 0.0.3
homepage: https://github.com/xErik/nftgen


environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  crypto: ^3.0.2
  image: ^4.0.8
  io: ^1.0.3
  path: ^1.8.3
