name: nftgen
description: NFT unique image generator and metadata analyzer, available as Dart package, CLI, EXE.
version: 0.0.6
repository: https://github.com/xErik/nftgen
issue_tracker: https://github.com/xErik/nftgen/issues
keywords: nft, crypto

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_lints: ^2.0.0
  archive: ^3.3.6
  commandline_or_gui_windows: ^2.1.2

dependencies:
  flutter:
    sdk: flutter
  args: ^2.3.1
  crypto: ^3.0.2
  duration: ^3.0.12
  humanize_big_int: ^1.0.1
  image: ^4.0.8
  io: ^1.0.3
  path: ^1.8.2
  collection: ^1.16.0
  filesize: ^2.0.1
  isolate_pool_2: ^1.0.4
  universal_disk_space: ^0.2.3
